### ISSUE TITLE
Ampache theme

### ISSUE THREAD

**Issue by lachlan-00** [Andrew-McGee/foam#3]
i'm close to the ampache dark theme so something similar would be good to include

```
  // #04 Ampache - Uncomment to use
  $theme[4]['name'] = 'ampache-dark';     // Name
  $theme[4]['colrfgd1'] = '#222222'; // Foreground
  $theme[4]['colrbgd1'] = '#1D1D1D'; // Background
  $theme[4]['colrfnt1'] = '#888888'; // Main text
  $theme[4]['colrfnt2'] = '#ffffff'; // Bright text
  $theme[4]['colrfnt3'] = '#555555'; // Dark text
  $theme[4]['colrhilt'] = '#f49600'; // Highlight

  // #05 Ampache - Uncomment to use
  $theme[5]['name'] = 'ampache-light';     // Name
  $theme[5]['colrfgd1'] = '#f8f8f8'; // Foreground
  $theme[5]['colrbgd1'] = '#d8d8d8'; // Background
  $theme[5]['colrfnt1'] = '#000000'; // Main text
  $theme[5]['colrfnt2'] = '#1990db'; // Bright text
  $theme[5]['colrfnt3'] = '#ffffff'; // Dark text
  $theme[5]['colrhilt'] = '#157dbf'; // Highlight

```

looks good though. the light theme needs some work with highlighting but it's got the colours at least

![image](https://user-images.githubusercontent.com/1305249/119816518-22e99180-bf30-11eb-9696-ab6afa2d26ad.png)

![image](https://user-images.githubusercontent.com/1305249/119816570-31d04400-bf30-11eb-9a63-58a654506ef0.png)

![image](https://user-images.githubusercontent.com/1305249/119819146-685b8e00-bf33-11eb-8cfa-cb6afb9ae842.png)

![image](https://user-images.githubusercontent.com/1305249/119819201-75787d00-bf33-11eb-9635-1041e763eed4.png)

**Comment by Andrew-McGee** [comment]
Thanks heaps - these look great. Added them in. 

It reminds me there are still some elements not using the variables. Some are still using standard fomantic colours. Eg. The highlight colour on the sliders needs an override in CSS.

Also the settings menu item never wants to play nice - it's on the list to investigate.

Once I finish the final functions my next sweep is fixing all the design glitches.

**Comment by Andrew-McGee** [comment]
All the highlights now honour the theme highlight colour - including sliders. Makes the Ampache orange looks great on the dark theme. Even the favourite stars use highlight now. :)

**Comment by lachlan-00** [comment]
now you're talking! I've set up with git and symbolic linked to my server public folder. i'll keep playing about but i think these colours will be fine as a base. keep it open if you want to use issues for theming concerns but the colours are in so i'm good

**Comment by Andrew-McGee** [comment]
I've come to like the ampache-light theme in foam a lot more now. At first it was a bit... 'bright', but now I've been using it more - it's fresh. :) I also fixed the highlighting so hovering over tracks now display correctly (was previously hard coded to white which obviously doesn't work with this theme).

**Comment by lachlan-00** [comment]
It's funny because the light theme is somehow really subversive in how much it grows on you.

It also helps giving you an opposite to check between regular dark themes

**Comment by lachlan-00** [comment]
just checked it out again, visually it all looks correct :)

**Comment by lachlan-00** [comment]
liking the light as is now, future state would be storing the preference inside the ampache database as your own pref
