### ISSUE TITLE
returned counts for playlists

### ISSUE THREAD

**Issue by lachlan-00** [Andrew-McGee/foam#5]
as foam is using only playlists for the counts (and we don't separate the counts in the handshake) i'm going to extend the returned data to put in a searches count
![image](https://user-images.githubusercontent.com/1305249/127593557-f6cba84c-acaf-4d29-abc9-44c38bfc18c0.png)

For a count that only includes playlist playlists i'm trying to think of a naming for that. because right now the api considers playlists to be both playlists and searches.

conversely if you just take away searches from playlists you have the count.

Would you prefer a playlists_only as an additional count or just keep the seaches?

**Comment by Andrew-McGee** [comment]
Hi mate - sorry I missed this one. I thought it was the old issue we had in here but I see that one is closed.

I'm not sure what you mean by searches count. Is it a count of all search results?

When I filter the playlists I use the hide_search=1 parm which excludes smartlists/searches from the results.

For my playlists view it looks like this:
?action=playlists&limit=24&hide_search=1

**Comment by Andrew-McGee** [comment]
Also - where's your most active chat? Still freenode IRC?

**Comment by lachlan-00** [comment]
hide_searches is probably a good name for it so I'll do another count of hide search

Telegram channel is where most of us are. (Or at least where I spend the most time)

**Comment by lachlan-00** [comment]
Although tbh, it should probably be just the item type. So playlists

**Comment by lachlan-00** [comment]
Going to close this.
All the objects need to return their number as the object. I need to follow the rules rather than the default options.

'playlist+search' will be the combined object and playlist will be the playlist count.
